import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-blue-600 text-white p-4">
          <div className="flex gap-6 font-semibold">
            <Link href="/">Home</Link>
            <Link href="/colleges">Colleges</Link>
            <Link href="/compare">Compare</Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}